
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-dining-s26-05
owner: ucsb-cs156-s26
repo_name: proj-dining-s26-05
pull_requests: [{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"jk/review-stats-repo-queries","number":48,"title":"Jk/review stats repo queries","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/48"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"jk/review-stats-skeleton","number":46,"title":"backend review stats skeleton + endpoint","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/46"},{"author":{"id":"U_kgDOCTjnkA","is_bot":false,"login":"JohnKim04","name":"John Kim"},"headRefName":"jk/users-util","number":44,"title":"util files for toggleable roles","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/44"},{"author":{"id":"U_kgDOBZt3Dw","is_bot":false,"login":"ibrahimgok01","name":"Ibrahim Gok"},"headRefName":"ig-EPIC14-finish-new-system","number":42,"title":"IG - Complete Transition to New Role System","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/42"},{"author":{"id":"MDQ6VXNlcjU0NTE5MDAw","is_bot":false,"login":"jdelpego","name":"Joaquin Del Pego"},"headRefName":"issue40-invalidate-each-cache-key","number":41,"title":"Invalidate each query key separately on mutation","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/41"},{"author":{"id":"U_kgDOCVHjzg","is_bot":false,"login":"elissaalawi","name":"Elissa Alawi"},"headRefName":"ea-review-edit","number":39,"title":"Implemented Review Edit Page and tests","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/39"},{"author":{"id":"U_kgDOCVHjzg","is_bot":false,"login":"elissaalawi","name":"Elissa Alawi"},"headRefName":"ea-mod-bug","number":35,"title":"Fixed bug where moderator gets errors when accessing moderator page","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/35"},{"author":{"id":"U_kgDOCbzrWw","is_bot":false,"login":"katskt","name":"Katie"},"headRefName":"kp-review-modal","number":29,"title":"Added Moderator Modal for accepting/rejecting user reviews + leaving feedback. ","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-05/pull/29"}]
